[pytest]
DJANGO_SETTINGS_MODULE = doctorhide.settings
python_files = tests.py test_*.py *_tests.py
testpaths = accounts iam vault organizations billing
addopts = --cov=. --cov-report=html --cov-report=term-missing --cov-branch --cov-fail-under=0
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
norecursedirs = .git .venv venv __pycache__ *.egg-info
