# Generated by Django 6.0.5 on 2026-05-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms_version',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
