# Generated by Django 6.0.5 on 2026-05-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
