# Generated by Django 6.0.5 on 2026-05-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_secret_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='idempotency_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
