# Generated by Django 6.0.5 on 2026-05-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_secret_idempotency_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='payload_type',
            field=models.CharField(choices=[('string', 'string'), ('binary', 'binary')], default='string', max_length=16),
        ),
    ]
