# Generated by Django 6.0.5 on 2026-05-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_secret_payload_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
