# Generated by Django 6.0.5 on 2026-05-30 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_secret_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(blank=True, default='', max_length=120)),
                ('action', models.CharField(max_length=64)),
                ('secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('outcome', models.CharField(default='', max_length=32)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='vault.project')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
