# Generated by Django 6.0.5 on 2026-05-30 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_auditevent_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphertext', models.TextField()),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vault.secret')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
