# Generated by Django 6.0.5 on 2026-06-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_webhookendpoint_webhookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requires_rekey',
            field=models.BooleanField(default=False),
        ),
    ]
