# Generated by Django 6.0.5 on 2026-06-02 14:03

import django.db.models.deletion
from django.db import migrations, models


def drop_legacy_secrets_and_keys(apps, schema_editor):
    """Prototyping shortcut: drop pre-Week-8 Secret and ProjectAPIKey rows.

    The Week 8 refactor changes the FK shape (``Secret.environment``
    replaces ``Secret.project``; ``ProjectAPIKey`` is renamed to
    ``EnvironmentAPIKey``). Pre-launch, we don't need to preserve any
    of this data — the project's test database is reseeded by Django on
    the next ``migrate`` run, and the user has confirmed "we are still
    prototyping, not live so we dont need to worry about migrations".

    When this code moves behind real customers, this RunPython must be
    replaced with an atomic-per-project data backfill: for every Project,
    seed a default ``Environment`` and re-point every Secret/ProjectAPIKey
    to it. The backfill is non-trivial because the seed needs crypto
    derived from a passphrase we don't have, so it must run as part of
    a maintenance window with the operator explicitly re-keying every
    project. See the Week 8 preamble in TODO.md.
    """
    # Use the historical model state so this migration is reproducible
    # even after the Project/Environment fields move. Avoid importing
    # the current ``vault.models`` (its shape has changed by the time
    # the migration is replayed in a fresh checkout).
    Secret = apps.get_model("vault", "Secret")
    ProjectAPIKey = apps.get_model("vault", "ProjectAPIKey")

    # SecretVersion has CASCADE on Secret, so dropping Secrets clears
    # version rows automatically. ProjectAPIKey stands alone.
    Secret.objects.all().delete()
    ProjectAPIKey.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_project_requires_rekey'),
    ]

    operations = [
        # 1. Drop the pre-Week-8 Secret + ProjectAPIKey rows. We do this
        # *before* removing the Project crypto columns so any
        # post_migrate signal that runs on the historical Project model
        # does not see partial state.
        migrations.RunPython(
            drop_legacy_secrets_and_keys,
            migrations.RunPython.noop,
        ),
        # 2. Remove the Project crypto columns. The model still exposes
        # them as read-only properties that delegate to
        # ``Project.default_environment`` (see ``vault/models.py``), so
        # the dozens of read-only call sites in views and tests keep
        # working through Phase 3.
        migrations.RemoveField(
            model_name='project',
            name='iterations',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requires_rekey',
        ),
        migrations.RemoveField(
            model_name='project',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='project',
            name='verifier',
        ),
        # 3. Add the Environment table. The Project FK is created with
        # the standard CASCADE + ``related_name='environments'`` so
        # ``project.environments.all()`` is the canonical lookup.
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('iterations', models.PositiveIntegerField(default=600000)),
                ('verifier', models.TextField()),
                ('requires_rekey', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='vault.project')),
            ],
            options={
                'ordering': ('project', 'slug'),
                'unique_together': {('project', 'name'), ('project', 'slug')},
            },
        ),
    ]

